Add over the moon coordinator
RoboSats/robosats pull request #1591
Opened 2024-11-01 14:52 UTC by KoalaSat

## What does this PR do?
Fixes #1586

Add over the moon coordinator

## Checklist before merging
- [ ] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

2024-11-01 16:36 UTC, otmooon commented on frontend/static/federation.json
> +  "overthemoon": {
`"overthemoon"` can be changed to `"moon"`

2024-11-01 16:36 UTC, otmooon commented on frontend/static/federation.json
> +    "shortAlias": "overthemoon",
`"shortAlias"` can be changed to `"moon"`, everything else looks good. Thank you so much!

2024-11-01 16:39 UTC, otmooon requested changes
Just a couple of comments shortening "overthemoon" to "moon". Everything else looks good (to me at least). Thank you so much!

2024-11-01 20:42 UTC, KoalaSat commented
Thanks for the review! These alias you see here are just used only on the tech side so it doesn't really affects or reach to the end user

2024-11-02 18:08 UTC, Reckless-Satoshi commented
Hey, this coordinator won't be reachable for those using the self-hosted app.

We need to add the correct nginx configs in https://github.com/RoboSats/robosats/tree/main/nodeapp/coordinators

It's not too relevant. But I also favor `moon` over `overthemoon` . Mostly because the short alias will become part of URLs and more concise urls are always nice.

2024-11-02 20:01 UTC, merged